### ISSUE TITLE
Fix text, remove spacing in the middle of the word "לאסוף"

### ISSUE THREAD

**Issue by iddanh** [Ezer-Lachaim/EZLA#152]
![Image](https://user-images.githubusercontent.com/12518219/261803261-317b293e-f890-4850-be60-c9a93dab3d38.png)

**Comment by LEVI-RIVKIN** [comment]
@iddanh 
I think this issue happened locally for someone.
I couldn't find a space there through the history of the file.

In any case it's fine now.
