### ISSUE TITLE
Enlarge font size in fields and hint text - across the board.

### ISSUE THREAD

**Issue by iddanh** [Ezer-Lachaim/EZLA#158]

**Comment by OrleeTal** [comment]
Hint text appears in the field, before the user starts typing,
The size is 18=? enlarge to 20px, in all screens.

![Image](https://github.com/Ezer-Lachaim/EZLA/assets/137285852/54071faf-97eb-4b72-a63b-a92852666dd8)

**Comment by OrleeTal** [comment]
@LEVI-RIVKIN @iddanh Was this task done?

**Comment by YankiBaras** [comment]
I took care of it and sent PR.

**Comment by YankiBaras** [comment]
> [@YankiBaras](https://github.com/YankiBaras) [@yitshak](https://github.com/yitshak) The font size looks great in the passenger's side, I didn't see any change in the Drivers screens.

@OrleeTal 
למיטב הבנתי המשימה הוגדרה על צד הנוסע, כדי שנוסעים שמתקשים בראייה וכדו' יוכלו לראות יותר טוב. לנהג יש מסכים רבים, עם פיגמה מפורטת מאד. ככל שיש להגדיל את זה גם בצד הנהג, צריך להגדיר זאת בפירוט בפיגמה.
