### ISSUE TITLE
The driver's name appears on the passenger side as "undefined."

### ISSUE THREAD

**Issue by OrleeTal** [Ezer-Lachaim/EZLA#173]
The driver's name appears on the passenger side as "undefined."
When I use: sharon.d@redis.com
 as the driver, the driver's name appears as "undefined."

Is it a general problem or just specific to Sharon?

**Comment by iddanh** [comment]
This user was created a long time ago before many new fixes, not relevant for new users.
Closing this issue.

@maorohana-redis Can you please remove all of our test users from the DB?
