### ISSUE TITLE
Email validation fails on valid email

### ISSUE THREAD

**Issue by OrleeTal** [Ezer-Lachaim/EZLA#178]
Email field: Not clear why the error message appears; perhaps there is spacing?
In any case: Spacing should be ignored to prevent errors as much as possible.
See screenshot:

![Image](https://github.com/Ezer-Lachaim/EZLA/assets/137285852/d4fae6d2-34d0-4ca1-90e7-406cb04bff31)

**Comment by YankiBaras** [comment]
I can't reproduce this bug, either in code or in production
