### ISSUE TITLE
Add a push notification for drivers, everytime a new ride request come in

### ISSUE THREAD

**Issue by OrleeTal** [Ezer-Lachaim/EZLA#181]
Add a push notification for drivers every time a new ride request comes in.

**Comment by OrleeTal** [comment]
@tomnaor The push notification is not working on my iPhone.
Ask additional people to test; I asked Nathan.
Perhaps it has to do with the phone settings.

**Comment by tomnaor** [comment]
Can you please describe the steps you took to raise a new notification? @OrleeTal

**Comment by OrleeTal** [comment]
@tomnaor 
1. Logged in as a driver on my phone 
2. Added a new drive via the backoffice on the desktop
3. The new request appears in the list - but no push sent on my phone

I also asked Nathan to test with his Android, but it didn't work for him either.

**Comment by tomnaor** [comment]
Are you getting notifications at all from the browser? Maybe you did not give permission for the app? 
I just created a new ride from the back office and I got the notification on my desktop from Chrome.

@OrleeTal
