### ISSUE TITLE
Drivers app, the list of awaiting rides doesn't refresh automatically on phones, in order to see the  rides users need to close the app and re-open it.

### ISSUE THREAD

**Issue by OrleeTal** [Ezer-Lachaim/EZLA#188]
Drivers app, the list of awaiting rides doesn't refresh automatically on phones.
To see the rides users need to close the app and re-open it.
The rides do show app when the app is displayed on the desktop.
See the screenshots below.

**Comment by OrleeTal** [comment]
![WhatsApp Image 2023-08-26 at 10 35 45 PM](https://github.com/Ezer-Lachaim/EZLA/assets/137285852/776d6e13-d788-4a97-a78a-51e87074e8ef)
![WhatsApp Image 2023-08-26 at 10 35 23 PM](https://github.com/Ezer-Lachaim/EZLA/assets/137285852/ad7c2479-5275-450a-b93e-d29c421736eb)

**Comment by IsraelKariti** [comment]
![Image](https://github.com/Ezer-Lachaim/EZLA/assets/89970476/3edf70bb-29f1-49ba-899b-94c550435fda)

**Comment by IsraelKariti** [comment]
אני לא מצליח לשחזר את הבאג, אצלי באמולטור זה עובד תקין

**Comment by OrleeTal** [comment]
האם הרשימה מתרעננת באופן אטומטי כאשר נכנסת קריאה חדשה?
האם בדקת על טלפון או על הדסקטופ שלך?

**Comment by iddanh** [comment]
אני חושב שזה תוקן כבר בעקבות תיקונים אחרים שנעשו, אני מעביר את זה לdone.
@OrleeTal אם את רואה שזה קורה שוב אז תעבירי את הטיקט הזה חזרה לtodo
