### ISSUE TITLE
"Open ride" ticket enhancements in list, driver's side [HIGH]

### ISSUE THREAD

**Issue by iddanh** [Ezer-Lachaim/EZLA#213]
The following changes should be made to the Open Ride ticket:
1. Add the passenger's first name
2. ~~Add an icon and link to open WAZE~~ (already done)
3. Change: המתנה ל- המתנה לאיסוף

![Image](https://github.com/Ezer-Lachaim/EZLA/assets/137285852/e1700323-eacb-43c6-9726-984b1d1848c9)

**Comment by OrleeTal** [comment]
@iddanh Also add comment, see example:


![Image](https://github.com/Ezer-Lachaim/EZLA/assets/137285852/d785f7ae-98d4-498d-8b91-06b6cd5e6eac)
