### ISSUE TITLE
"Waiting for driver screen" updates (passenger side) [HIGH]

### ISSUE THREAD

**Issue by iddanh** [Ezer-Lachaim/EZLA#214]
The waiting for driver pop-up should change to a separate screen, as follows:
1. Screen instead of pop-up + back button
2. Textual changes
3. canceling a ride or tapping back => should present the warning message: Are you sure...

![Image](https://github.com/Ezer-Lachaim/EZLA/assets/137285852/6bbb743b-4ae8-4fd6-bc3d-00afee294d2c)

**Comment by OrleeTal** [comment]
@iddanh The bottom part of the screen is cut off; see screenshot.
Can you position the display above the browser's URL bar? Like you did in the opening screen.


![Image](https://github.com/Ezer-Lachaim/EZLA/assets/137285852/f6898e91-db5b-4442-a545-5a10ab7987bc)

**Comment by iddanh** [comment]
fixed

**Comment by OrleeTal** [comment]
Moved to done.
