### ISSUE TITLE
After a driver was found, the passenger's screen doesn't auto-refresh [HIGH]

### ISSUE THREAD

**Issue by iddanh** [Ezer-Lachaim/EZLA#215]
This screen needs to disappear automatically once a driver selects the ride; currently, passengers need to refresh:

![Image](https://github.com/Ezer-Lachaim/EZLA/assets/137285852/83a74337-0e1b-43c3-81bf-49f7dfc2c3c4)

**Comment by OrleeTal** [comment]
The Passenger's screen doesn't refresh after a driver selects the drive or as he arrives to pick up the passenger.
It is constantly stuck on "waiting to find a driver screen", see above

**Comment by LEVI-RIVKIN** [comment]
@iddanh @OrleeTal 
I am not able to reproduce on local environment. 
Do you have any more info or was this already resolved?

**Comment by OrleeTal** [comment]
Steps to reproduce:
Passenger side: Try ordering a ride as a passenger. The screen changes to
"waiting for driver".
Driver side: Login as a driver and select the drive
Passenger side: the screen is still stuck on  "waiting for driver".
Driver: Reached the passenger's location
Passenger side: the screen is still stuck on  "waiting for driver".

**Comment by LEVI-RIVKIN** [comment]
@OrleeTal 
I have tried these steps and it seems to be working fine.. 
Can you try to reproduce and see if it's still happening?

**Comment by OrleeTal** [comment]
@LEVI-RIVKIN I'll try again.

**Comment by OrleeTal** [comment]
@LEVI-RIVKIN A recording of passenger and driver flow on my phone.

**Comment by LEVI-RIVKIN** [comment]
@OrleeTal Can you (or somebody) test on production and move to done?
