### ISSUE TITLE
Title of the order ride screen [Medium]

### ISSUE THREAD

**Issue by iddanh** [Ezer-Lachaim/EZLA#217]
Currently the title is displayed in Male language, need to change to:
שלום! צריכים הסעה?

![Image](https://github.com/Ezer-Lachaim/EZLA/assets/137285852/550bd55e-fdbf-4cd6-951d-3e51637549f3)

**Comment by OrleeTal** [comment]
@iddanh השארת את המילה נוסע בלשון זכר
עדיף להוריד את המילה
