### ISSUE TITLE
A ride request doesn't appear in the drivers' list of requests- see first entery in screenshot

### ISSUE THREAD

**Issue by OrleeTal** [Ezer-Lachaim/EZLA#223]
<img width="1441" alt="image" src="https://github.com/Ezer-Lachaim/EZLA/assets/137285852/4ed63615-c233-4dad-af22-f62002ce3754">
**Describe the bug**

A short description of the bug.

**To reproduce**

Steps to reproduce the behavior.

**Expected behavior**

A description of what you expected to happen.

**Additional information**

Any additional information that is relevant to the problem.

**Comment by aviv-taori** [comment]
#223

In the current version there is no such bug, by talking to Orly you can close the bug
