### ISSUE TITLE
Enable ordering a ride with no need to register first (Passenger side)

### ISSUE THREAD

**Issue by OrleeTal** [Ezer-Lachaim/EZLA#234]
- The passager will always land in the opening. page
- Tap the "Order ride" button
- "Order ride screen" Fill in the fields and order a ride
- Wait for the driver to be found 
- Continue with the regular process as currently implemented
 See Figma: https://www.figma.com/file/n5xrJSqVtygZ9hqww1Pf2a?node-id=502:7112&mode=design#581745776

**Comment by tomnaor** [comment]
Maybe the first screen can be something similar to this screen, where we will explain a little bit about the current service and how we now support all kinds of transportation needs. @OrleeTal 

![Image](https://github.com/Ezer-Lachaim/EZLA/assets/26869573/0da94216-20c2-4278-be17-d5216c1bcb50)

**Comment by OrleeTal** [comment]
הטקסט כבר שונה לזה:
[image: image.png]

**Comment by tomnaor** [comment]
I don't see the image you sent. @OrleeTal

**Comment by OrleeTal** [comment]
https://www.figma.com/file/n5xrJSqVtygZ9hqww1Pf2a?node-id=502:7112&mode=design#581745776

Tom, Let me know if you see it.

**Comment by OrleeTal** [comment]
@tomnaor, I don't see the updates yet, do they still need to be released?

**Comment by OrleeTal** [comment]
@tomnaor Looking good!
Comments:
1. Need to add the Terms & conditions confirmation at the bottom
2. When canceling a ride from the Back office, it should also cancel it for the user and trigger the message that the driver canceled the ride.

**Comment by OrleeTal** [comment]
@tomnaor כנראה שיש באג כללי שלא ניתן לבטל נסיעות, קיבלתי פניה מנוסע שניסה

**Comment by OrleeTal** [comment]
@tomnaor מתי תוכל לטפל בתיקונים?

**Comment by OrleeTal** [comment]
@LEVI-RIVKIN What's left in this ticket:
נשאר להוסיף את התקנון ומדיניות הפרטיות, זהו שדה חובה. שני המסכים הללו קיימים ופותחו, אז צריך לחבר את הלינקים לכל אחד מן המסכים.
בעבר היה באג שכאשר חזרו מצפייה במסכים הללו כל השדות של הטופס התנקו" אז צריך לבדוק.
