### ISSUE TITLE
SMS reminders to passengers after a driver started driving to the pickup location and when the driver arrives at the picup location

### ISSUE THREAD

**Issue by OrleeTal** [Ezer-Lachaim/EZLA#238]
SMS reminders to passengers after a driver started driving to the pickup location and when the driver arrives at the picup location.
See SMS messages in Figma file (in pink):
https://www.figma.com/file/n5xrJSqVtygZ9hqww1Pf2a?node-id=502:7112&mode=design#582590353

**Comment by LEVI-RIVKIN** [comment]
Duplicate of https://github.com/Ezer-Lachaim/EZLA/issues/252

**Comment by LEVI-RIVKIN** [comment]
Duplicate of https://github.com/Ezer-Lachaim/EZLA/issues/252
