### ISSUE TITLE
Enable sorting the "DRIVERS" screen in the backoffice by the following columns: Address, Volunteering area, number of seats and specials

### ISSUE THREAD

**Issue by OrleeTal** [Ezer-Lachaim/EZLA#245]
Enable sorting the "DRIVERS" screen in the back office by the following columns: Address, volunteering area, number of seats and specials. To help the call center find and contact volunteers who are relevant

<img width="944" alt="image" src="https://github.com/Ezer-Lachaim/EZLA/assets/137285852/813d0924-654b-4385-8901-a5b57a6f0327">

FIGMA:
https://www.figma.com/file/3UBN2ek01pmm2muttlrxYj?node-id=0:1&mode=design#599008421

**Comment by OrleeTal** [comment]
https://www.figma.com/file/n5xrJSqVtygZ9hqww1Pf2a?node-id=1196:40443&mode=design#590871182

This includes, additional features, not only the sorting functionality.

**Comment by OrleeTal** [comment]
z

**Comment by ZummyUX** [comment]
It is in the task #279 design
[Update link](https://www.figma.com/file/hhLq1zibZfO6uWSAbSl0Qg/%D7%A2%D7%96%D7%A8-%D7%9C%D7%97%D7%99%D7%99%D7%9D---%D7%A1%D7%9C%D7%A2?type=design&node-id=81-56558&mode=design&t=Ftax9DyVlN9OByHU-4)
