### ISSUE TITLE
Extend session login time

### ISSUE THREAD

**Issue by iddanh** [Ezer-Lachaim/EZLA#254]

**Comment by LEVI-RIVKIN** [comment]
This was done on top of the changes of #277, so a PR for this will be opened after the #277 PR is merged.

**Comment by yitshak** [comment]
Talk to @levi about verification for this fix

**Comment by LEVI-RIVKIN** [comment]
@OrleeTal This issue is done. I think it was tested by @YankiBaras in https://github.com/Ezer-Lachaim/EZLA/issues/275.

The way to test it is:
1. Login to the app.
2. Close the app and wait more than an hour.
3. Open the app again and see if you are required to login again (you shouldn't be).

**Comment by YankiBaras** [comment]
I tested it and it works.
