### ISSUE TITLE
Show a clear indication in the Back Office's menu regarding which page is selected, as defined in Figma

### ISSUE THREAD

**Issue by OrleeTal** [Ezer-Lachaim/EZLA#256]
Show a clear indication in the Back Office's menu regarding which page is selected, as defined in Figma (white background).
<img width="561" alt="image" src="https://github.com/Ezer-Lachaim/EZLA/assets/137285852/049b08fd-2101-43ef-8367-4e62ac0aa4b2">

**Comment by OrleeTal** [comment]
@yosi-miller @yitshak The indication is fixed,
But a new bug was created; the width of the navigation changes when navigating through the options; see below:
It needs to remain the same width as before.


![Image](https://github.com/Ezer-Lachaim/EZLA/assets/137285852/879aa8b7-3fd3-4683-a441-d36086b19f85)

**Comment by yosi-miller** [comment]
I opened new pull requests with a fix for this bug

**Comment by YankiBaras** [comment]
Looks good, solves the problem, can be transferred to production. A design according to the pygma should be sent later.
