### ISSUE TITLE
Update Opening page and driver's first login (textual changes only)

### ISSUE THREAD

**Issue by OrleeTal** [Ezer-Lachaim/EZLA#260]
Update the Openng page and driver's first login (textual changes only)
1. A few visual changes in the Opening page: add a clear button for Driver
2. First login page textual updates:

- Title text
- Hint text

FIGMA:
https://www.figma.com/file/3UBN2ek01pmm2muttlrxYj?node-id=1:5596&mode=design#599015992

**Comment by IsraelKariti** [comment]
יש לי שאלה לגבי הטיקט הזה
כתוב שמדובר בשינויים טקסטואליים בלבד
אני רואה שהכפתור "כניסה כמתנדב" לא מופיע אצלי בכלל
אני נמצא על הבראנץ feat/open to all
בתמונה אפשר לראות את ההבדל בין הפיגמה (משמאל) לבין האפליקציה שעולה אצלי במחשב ובטלפון (מימין)
האם כחלק מהטיקט הזה צריך להוסיף את הכפתור הזה? או שאני מפספס משהו?
תודה ושבת שלום

![Image](https://github.com/Ezer-Lachaim/EZLA/assets/89970476/ee70b281-dc03-43c4-a702-8fbfca04c057)

**Comment by OrleeTal** [comment]
@IsraelKariti כן, צריך להוסיף את הכפתור הנוסף, זה שכפול של הכפתור הקיים בשינוי צבעוני

**Comment by IsraelKariti** [comment]
אני מניח שאם זה המצב, אז כנראה גם צריך לייצר את כל המסכים שמגיעים לאחר לחיצה על הכפתור הזה
מדובר במטלה יותר גדולה ממה שחשבתי בהתחלה (=שינויים טקסטואליים בלבד)
לכן אני אוריד את המטלה הזאת ממני לעת עתה

**Comment by OrleeTal** [comment]
@IsraelKariti @iddanh I don't see the updated screen:

FIGMA:
https://www.figma.com/file/3UBN2ek01pmm2muttlrxYj?node-id=364:101836&mode=design#599015992


![Image](https://github.com/Ezer-Lachaim/EZLA/assets/137285852/d4039df5-1a37-4de5-8f31-6db13c8f992d)

**Comment by iddanh** [comment]
You cannot see it yet because it was not merged to feat/open-to-all branch yet. @LEVI-RIVKIN said he will do it

**Comment by LEVI-RIVKIN** [comment]
@OrleeTal This should be in production, can you test and close the issue?

**Comment by OrleeTal** [comment]
@LEVI-RIVKIN שתי הערות:
1. TYPO במסך פתיחה במילה מתנדבים

![Image](https://github.com/Ezer-Lachaim/EZLA/assets/137285852/cc7a535e-68e4-4bee-8459-ac60dc1cc44f)

2. בלחיצה על  כניסה ראשונה כמתנדב
הטקסט HINT צריך להיות שונה
ראה צילום מסך


![Image](https://github.com/Ezer-Lachaim/EZLA/assets/137285852/06d1bd34-1b20-4705-9e87-27a5599c10be)

**Comment by LEVI-RIVKIN** [comment]
@OrleeTal 
1. יתוקן
2. כרגע הטקסט הוא כפי שהיה בפיגמה כשעשיתי, אני רואה רק שהשתנה ה"האימייל שאיתו נרשמתם", זה היה "האימייל שנרשמתם איתו". יתוקן.

**Comment by LEVI-RIVKIN** [comment]
@OrleeTal You can test and close.

**Comment by OrleeTal** [comment]
@LEVI-RIVKIN עדיין לא רואה שה HINT טקסט השתנה

כך זה נראה אצלי:

![Image](https://github.com/Ezer-Lachaim/EZLA/assets/137285852/873b4fe9-35b1-447b-a9e0-4fca68148ce1)

**Comment by LEVI-RIVKIN** [comment]
@OrleeTal ה HINT מופיע רק כשאת בפוקוס על השדה בדומה לצורה שבה מופיע ה HINT במקומות אחרים באפליציה, כמו ב login ובהזמנת נסיעה

**Comment by OrleeTal** [comment]
@LEVI-RIVKIN צודק
