### ISSUE TITLE
Passengers cannot cancel ride (may be connected to #234)

### ISSUE THREAD

**Issue by OrleeTal** [Ezer-Lachaim/EZLA#263]
Passengers cannot cancel the ride, the cancel button doesn't work and they are stuck on that screen with no way out.

**Comment by LEVI-RIVKIN** [comment]
@OrleeTal
I was able to cancel a ride from the passenger ride screen on local environment.
Do you have any more info or was this already resolved?

**Comment by OrleeTal** [comment]
I don't know what the difference is between the local environment.
But on my phone (iOS) I am unable to cancel a ride as a passenger.

**Comment by OrleeTal** [comment]
I will.

**Comment by LEVI-RIVKIN** [comment]
@OrleeTal Can you (or somebody) test on production and move to done?
