### ISSUE TITLE
After passenger creates a new ride the page is in "טוען..." state indefinitally

### ISSUE THREAD

**Issue by IsraelKariti** [Ezer-Lachaim/EZLA#271]
To recreate bug:
1. הזמן הסעה חדשה
2. Fill in the ride details
3. Click on "הזמינו נסיעה" on the buttom of the page
4. notice the page is "טוען..." 
-> While debugging it seems that the api call to RideApi doesn't return even after long waiting
-> The ride shows correctly on the driver side

![Image](https://github.com/Ezer-Lachaim/EZLA/assets/89970476/8f8cb7ed-2754-4e0e-bac0-f11b1d6e07ca)

![Image](https://github.com/Ezer-Lachaim/EZLA/assets/89970476/1e3b4c80-5689-4577-a0c0-89eb71fd4d72)

**Comment by yitshak** [comment]
This back is no longer relevant
