### ISSUE TITLE
Driver's rides dashboard when login expires

### ISSUE THREAD

**Issue by OrleeTal** [Ezer-Lachaim/EZLA#275]
Driver's rides dashboard when login expires.

The screen stops displaying rides (although there are active rides).
The Logout button disappears
The user is "stuck" and cannot close or navigate away.

We need to lengthen the timeout and, when it does expire, return the user to the login screen.

FIGMA:
https://www.figma.com/file/3UBN2ek01pmm2muttlrxYj?node-id=0:1&mode=design#599007908

**Comment by OrleeTal** [comment]
It also happens in passengers screen.

**Comment by OrleeTal** [comment]
@LEVI-RIVKIN Did you fix these issues in another ticket, and return the driver to login screen?

**Comment by LEVI-RIVKIN** [comment]
@OrleeTal Yes, this will be fixed by issue #277 which is waiting for the staging environment to be deployed.

@iddanh @tomnaor @maorohana-redis Maybe we need to think about merging this before the staging env is ready. The route guards seem to be important and setting up the staging env takes a bit too long..

**Comment by OrleeTal** [comment]
@LEVI-RIVKIN I tried the following scenario:
1. Logged in as a driver
2. closed the tab 
3. Reopened the link
I expected the system to log me in automatically and show me the RIDES screen.
But nothing happened. I had to type everything from the very beginning.
Is that what was supposed to happen?

**Comment by YankiBaras** [comment]
> [@LEVI-RIVKIN](https://github.com/LEVI-RIVKIN) I tried the following scenario:
> 
> 1. Logged in as a driver
> 2. closed the tab
> 3. Reopened the link
>    I expected the system to log me in automatically and show me the RIDES screen.
>    But nothing happened. I had to type everything from the very beginning.
>    Is that what was supposed to happen?

I tried the above steps and they worked as expected.

**Comment by ZummyUX** [comment]
[Updated link](https://www.figma.com/file/hhLq1zibZfO6uWSAbSl0Qg/%D7%A2%D7%96%D7%A8-%D7%9C%D7%97%D7%99%D7%99%D7%9D---%D7%A1%D7%9C%D7%A2?type=design&node-id=339-57661&mode=design&t=Ftax9DyVlN9OByHU-4)
