### ISSUE TITLE
Enable editing Driver's details in the Back Office

### ISSUE THREAD

**Issue by OrleeTal** [Ezer-Lachaim/EZLA#282]
Enable editing Driver's details in the Back Office
Waiting for Graphic design

**Comment by ZummyUX** [comment]
[Update link](https://www.figma.com/file/hhLq1zibZfO6uWSAbSl0Qg/%D7%A2%D7%96%D7%A8-%D7%9C%D7%97%D7%99%D7%99%D7%9D---%D7%A1%D7%9C%D7%A2?type=design&node-id=81-59090&mode=design&t=Ftax9DyVlN9OByHU-4)
