### ISSUE TITLE
Connect Google docs' output (where drivers register) to the admin tool. OR Develop driver registration on app  TBD

### ISSUE THREAD

**Issue by OrleeTal** [Ezer-Lachaim/EZLA#291]
Currently, drivers are registering on Google Docs.
The operators need to copy all the data to the admin manually.
This is time-consuming and creates human error.

The output of the Google Docs should automatically create a driver in the system in "draft" status.
If the email already exists in the system, it should show an error message in the form created in the admin.

Figma:
https://www.figma.com/file/3UBN2ek01pmm2muttlrxYj?node-id=448:57254&mode=design#613068382

**Comment by yosi-miller** [comment]
I need access to the correct Google form to develop this feature.

**Comment by yosi-miller** [comment]
In Back Office it only shows the city of residence but in Google form there is a request for other information, is that correct?


![Image](https://github.com/Ezer-Lachaim/EZLA/assets/129267449/613ae138-d028-4a83-ab71-07f75bcc6b1d)


![Image](https://github.com/Ezer-Lachaim/EZLA/assets/129267449/f946eacb-d50f-4049-a3ed-6df8268d0eb0)
