### ISSUE TITLE
Update Ride - opens a white screen

### ISSUE THREAD

**Issue by OrleeTal** [Ezer-Lachaim/EZLA#298]
@IsraelKariti אחרי כמה שעות שזה עבד תקין - עדכון נסיעה הפסיק לעבוד - מראה מסך ריק -  ייתכן ועדכנו גירסה

**Comment by IsraelKariti** [comment]
אצלי זה עובד
אולי תוכל לעזור?
 @iddanh 


![Image](https://github.com/Ezer-Lachaim/EZLA/assets/89970476/cff1c14d-f415-4c52-8d06-27078a1993c2)

**Comment by LEVI-RIVKIN** [comment]
@IsraelKariti דיברתי עם אורלי בבוקר שאטפל בזה, אבל אתה מוזמן.. פשוט תעביר אליך.

@OrleeTal מצטרף לשאלה של ישראל. גם אצלי זה לא משתחזר. צריך איזה סרטון או הכי טוב איזו פגישה קצרה לראות איפה בדיוק הבעיה עם היוזר שלך בפרודקשן.

**Comment by LEVI-RIVKIN** [comment]
@IsraelKariti סליחה, קבעתי עם אורלי על משימות אחרות, העברתי אליך

**Comment by LEVI-RIVKIN** [comment]
@IsraelKariti הבעיה קורית כאשר מייצרים נסיעה דרך הבקאופיס ללא בקשות מיוחדות.

צריך לוודא שהשדה `specialRequest` נשמר כמו שצריך בחלונית הזו של יצירת נסיעה דרך הבקאופיס בדומה למה שנשמר ביצירת נסיעה ע"י נוסע.

**Comment by OrleeTal** [comment]
***@***.***
534545fdfdf
זה היוזר וסיסמא של הבק אופיס

תעדכנו. תודה

**Comment by IsraelKariti** [comment]
@LEVI-RIVKIN הבנתי, תודה:) מעניין אם זה לא היה ככה גם קודם, כי אני לא נגעתי בחלק של יצירת נסיעה מהבקאופיס, אבל כן עבדתי עם נסיעות שיצר נוסע, וגם שם לא היו בקשות מיוחדות וזה דווקא עבד. אבל אנסה לנבור

@OrleeTal 
היי אורלי, אני בשוונג של #282 
מאמין שאסיים מחר, ואז אתפנה ל#298

**Comment by OrleeTal** [comment]
מצוין, זה יזרים חמצן לחמ"ל. תודה

**Comment by OrleeTal** [comment]
@IsraelKariti @iddanh 
הי ישראל, הרשומות האחרונות במסך עובדים תקין, אבל רשומות ישנות יותר (ראה מוקף בכחול) עדיין נפתח מסך לבן. תוכל לבדוק שוב. תודה
![Image](https://github.com/Ezer-Lachaim/EZLA/assets/137285852/d682a08f-9716-45db-bae6-32d9040302fc)
