### ISSUE TITLE
Cancelling a ride in the backoffice, doesn't cancel it in the passenger's app and doesn't pop up a message.

### ISSUE THREAD

**Issue by OrleeTal** [Ezer-Lachaim/EZLA#302]
When canceling a ride from the Back office, it should also cancel it for the user and trigger the message that the ride was canceled (similar to the message displayed when the driver cancels a ride) and return them to the ORDER NEW RIDE screen. There's a dead end as the user can't cancel the ride after it's been canceled from the Bck office.

FIGMA
https://www.figma.com/file/3UBN2ek01pmm2muttlrxYj?node-id=545:60083&mode=design#617145899

**Comment by LEVI-RIVKIN** [comment]
@OrleeTal This should be in production, can you test and close the issue?

**Comment by LEVI-RIVKIN** [comment]
אפשר סרטון או משהו? כי אצלי זה לא קורה

**Comment by OrleeTal** [comment]
סרטון הדגמה

https://github.com/Ezer-Lachaim/EZLA/assets/137285852/2cc30fb2-fe49-41d4-938e-64f5136cae48

**Comment by LEVI-RIVKIN** [comment]
@OrleeTal Found the problem. I should have tested it better after I merged it into the 'open-to-all' branch.

@iddanh https://github.com/Ezer-Lachaim/EZLA/pull/324

**Comment by LEVI-RIVKIN** [comment]
@OrleeTal You can test and close now.
