### ISSUE TITLE
Ride description field - extend number of characters for 50 characters to 60.

### ISSUE THREAD

**Issue by OrleeTal** [Ezer-Lachaim/EZLA#320]
Ride description field - extend the number of characters from 50 to 60.
Needs to be updated in Backoffice, Passenger's and driver's screens.

**Comment by aviv-taori** [comment]
There is a requirement to increase the text field to 100 characters.

https://www.figma.com/file/3UBN2ek01pmm2muttlrxYj/MVP-Current-Design?type=design&node-id=1141-145616&mode=design&t=Du77OG5dG0lqF1HY-0

<img width="234" alt="Textfield" src="https://github.com/Ezer-Lachaim/EZLA/assets/134504658/faded681-94e0-40dc-839f-a3beead11c15">

**Comment by yitshak** [comment]
@aviv-taori בבקשה תבדוק את כלהמסכים ותראה לאורלי כדי שנבין שזה מה שהגודל בסדר

**Comment by OrleeTal** [comment]
@YankiBaras @aviv-taori @yitshak What's the difference between this task and #414?
It appears the same.
In staging it doesn't look this way, no scroll bar appears.

![Image](https://github.com/Ezer-Lachaim/EZLA/assets/137285852/0ac7e107-a062-4e09-bbf0-f729dcb19401)
