### ISSUE TITLE
Make 'open-to-all' feature an env config and merge it into `main` branch

### ISSUE THREAD

**Issue by LEVI-RIVKIN** [Ezer-Lachaim/EZLA#326]
The env variable `ALLOW_GUEST_RIDE_MODE=true` will activate the war mode.

**Comment by alon-redis** [comment]
@LEVI-RIVKIN - can you share what is "iopen to all" feature ? and what is the env config that I can set in order to enable / disable it?

**Comment by LEVI-RIVKIN** [comment]
Hi @alon-redis,

The "open to all" feature is a mode where anyone can book a ride through the app, even guests / not registered users. This feature was hastily developed for the war time in the branch named "feat/open-to-all". The purpose of this issue is to avoid maintaining two branches and allow us to enable / disable this feature using an env config.

The name of the evn config was added to the description of the issue.

**Comment by alon-redis** [comment]
@LEVI-RIVKIN @iddanh - how do I see the env config and control it?
I dont see in the back office page
