### ISSUE TITLE
New drivers, trying to make their first login via their ID number receive an error message (since 11.12.2023)

### ISSUE THREAD

**Issue by OrleeTal** [Ezer-Lachaim/EZLA#336]
**Describe the bug**

A short description of the bug.

**To reproduce**

Steps to reproduce the behavior.

**Expected behavior**

A description of what you expected to happen.

**Additional information**

Any additional information that is relevant to the problem.

**Comment by LEVI-RIVKIN** [comment]
@OrleeTal 
I wasn't able to reproduce this issue locally. Can you provide more details? 
Maybe open a test driver on the production backoffice and I'll try to login.
