### ISSUE TITLE
[Staging] The address link to WAZE, opens a download screen instead of directing to WAZE web page

### ISSUE THREAD

**Issue by OrleeTal** [Ezer-Lachaim/EZLA#343]
The address link to WAZE, opens a download screen instead of directing to WAZE's web page.
This happened on all screens; it used to work properly.
I haven't tested it in production.

![WhatsApp Image 2023-12-11 at 11 56 08 PM (2)](https://github.com/Ezer-Lachaim/EZLA/assets/137285852/ffe26ee1-67cb-445d-baaa-c45620f98256)
![WhatsApp Image 2023-12-11 at 11 56 08 PM (1)](https://github.com/Ezer-Lachaim/EZLA/assets/137285852/76b392ee-50a8-4a6e-9d8a-703bd546af90)
![WhatsApp Image 2023-12-11 at 11 56 08 PM](https://github.com/Ezer-Lachaim/EZLA/assets/137285852/c8960e08-55b5-4aca-ae6b-6eb94a572daf)

**Comment by OrleeTal** [comment]
@aviv-taori @yitshak  I tried testing it in the staging environment on my phone, and it doesn't open the WAZE navigation screen.
Is it in staging?

**Comment by yitshak** [comment]
generelly not reproducing
