### ISSUE TITLE
Editing Driver's details in the backend doesn't work - an error message appears

### ISSUE THREAD

**Issue by OrleeTal** [Ezer-Lachaim/EZLA#347]
Editing Driver's details in the backend doesn't work - an error message appears.
![image](https://github.com/Ezer-Lachaim/EZLA/assets/137285852/7ed1987b-c0d0-4358-965d-e79d07753a1a)

**Comment by yitshak** [comment]
לא נראה שמשתחזר בגרסה האחרונה, צריך לבדוק עוד פעם בפרודקשיין

**Comment by YankiBaras** [comment]
This bug no longer exists in production

‫בתאריך יום ב׳, 1 בינו׳ 2024 ב-10:54 מאת ‪Yitshak Yarom‬‏ <‪
***@***.***‬‏>:‬

**Comment by YankiBaras** [comment]
This bug no longer exists in production
