### ISSUE TITLE
The Passenger cannot cancel ride, the cancel button is disabled (this bug already occured in the past)

### ISSUE THREAD

**Issue by OrleeTal** [Ezer-Lachaim/EZLA#348]
Passenger cannot cancel ride, the cancel button is disabled (this bug already occured in the past).
![image](https://github.com/Ezer-Lachaim/EZLA/assets/137285852/8bbc9aeb-cfd1-485a-94fc-f9fbfa656982)

**Comment by yitshak** [comment]
לא נראה שמשתחזר בגרסה האחרונה, צריך לבדוק עוד פעם בפרודקשיין

**Comment by YankiBaras** [comment]
This bug no longer exists in production

‫בתאריך יום ב׳, 1 בינו׳ 2024 ב-10:53 מאת ‪Yitshak Yarom‬‏ <‪
***@***.***‬‏>:‬

**Comment by YankiBaras** [comment]
This bug no longer exists in production
