### ISSUE TITLE
Change the registration link to the updated drivers registration form.

### ISSUE THREAD

**Issue by OrleeTal** [Ezer-Lachaim/EZLA#353]
Change the registration link to the updated drivers' registration form (לחיצה על כאן)
The link should direct to: 
https://docs.google.com/forms/d/e/1FAIpQLSc_ZQfja7JKlKIR-_URVnqXc0uyE3L9oSMnV0mv5sWngvBwaw/viewform

Please check if this link appears anywhere else in the system and also change it.

<img width="387" alt="image" src="https://github.com/Ezer-Lachaim/EZLA/assets/137285852/18e7c606-56b3-4120-bc88-edd47cbd3ee6">

**Comment by ShrirangB** [comment]
@OrleeTal please check the changes
