### ISSUE TITLE
that the phone number of the trip will appear to the driver

### ISSUE THREAD

**Issue by yosi-miller** [Ezer-Lachaim/EZLA#362]
On the driver's trip screen, in the call button who ordered the trip, the text appears - "Request a ride" and no cell phone number appears

You must switch to display the mobile phone number.

![Uploading IMG_2187.JPG…]()

**Comment by yosi-miller** [comment]
![IMG_2187](https://github.com/Ezer-Lachaim/EZLA/assets/129267449/5f8e35c9-3c32-45c5-8071-6f328aed7f33)

**Comment by yosi-miller** [comment]
need to view the design in Figma to complete this bag

**Comment by OrleeTal** [comment]
@yosi-miller @yitshak We will postpone this task as part of the FUTURE RIDE; you can see the design in this flow.
But in the future, send me a note with a request for design, but don't move it to WAITING FOR TESTING.

**Comment by YankiBaras** [comment]
The feature works as expected. Can be transferred to production.
