### ISSUE TITLE
New Ride - Use MUI number input for number of passengers input

### ISSUE THREAD

**Issue by LEVI-RIVKIN** [Ezer-Lachaim/EZLA#370]
Passenger Figma: 
https://www.figma.com/file/3UBN2ek01pmm2muttlrxYj/MVP-Current-Design?type=design&node-id=1306-363555&mode=dev

Backoffice Figma:
https://www.figma.com/file/3UBN2ek01pmm2muttlrxYj/MVP-Current-Design?type=design&node-id=1301-331405&mode=dev

MUI Component: 
https://mui.com/base-ui/react-number-input/

**Comment by OrleeTal** [comment]
@YankiBaras As you cannot reduce the number of passengers below zero, the minus button should appear disabled when the number of passengers = 1.

![Image](https://github.com/Ezer-Lachaim/EZLA/assets/137285852/0a982c53-4e4f-4b84-a151-fdfad6eb7f42)
