### ISSUE TITLE
New Ride - Use multi select list for special requests

### ISSUE THREAD

**Issue by LEVI-RIVKIN** [Ezer-Lachaim/EZLA#372]
Passenger Figma:
https://www.figma.com/file/3UBN2ek01pmm2muttlrxYj/MVP-Current-Design?type=design&node-id=1306-363561&mode=dev

Backoffice Figma:
https://www.figma.com/file/3UBN2ek01pmm2muttlrxYj/MVP-Current-Design?type=design&node-id=1301-331414&mode=dev

MUI Component: 
https://mui.com/material-ui/react-select/#checkmarks

**Comment by OrleeTal** [comment]
@YankiBaras @yitshak The list of options appears in unexpected places and is hard to understand; it should appear the way it appear in the screenshot with the V (see attached below)

![Image](https://github.com/Ezer-Lachaim/EZLA/assets/137285852/65c85575-f8b8-4b84-8e2d-26a8b765193f)



![Image](https://github.com/Ezer-Lachaim/EZLA/assets/137285852/a24461f1-3ead-4591-b049-2ee012a265bb)



![Image](https://github.com/Ezer-Lachaim/EZLA/assets/137285852/fc54d6ff-728d-4468-85d6-01b3612a3b08)

**Comment by YankiBaras** [comment]
@OrleeTal
 ככל שיש מספיק מקום מהמיקום של ה'בקשות המיוחדות' במסך ועד תחתית המסך - הממשק נפתח כצפוי. 
הבעיה מתחילה כאשר מנסים לפתוח את ה'בקשות המיוחדות' כאשר אין מספיק מקום במסך מתחת, ואז הוא נפתח במקום 
 שיש לו, שזה על חשבון הקומפוננטה עצמה.
מה צריך להיות לדעתך כאשר אין מספיק מקום בעמוד לפתוח את כל הבקשות המיוחדות?

**Comment by YankiBaras** [comment]
According to Zami, this is the behavior of the MUI component, and no other behavior should be expected.

**Comment by yitshak** [comment]
We will resolve this issue
