### ISSUE TITLE
New Ride - Change title

### ISSUE THREAD

**Issue by LEVI-RIVKIN** [Ezer-Lachaim/EZLA#373]
Figma:
https://www.figma.com/file/3UBN2ek01pmm2muttlrxYj/MVP-Current-Design?type=design&node-id=663-66356&mode=dev

**Comment by YankiBaras** [comment]
I didn't understand exactly what the mission was. Even now the title is 'שלום! צריכים הסעה?'

**Comment by LEVI-RIVKIN** [comment]
@YankiBaras I guess you should only replace `!` with `,` :)
