### ISSUE TITLE
Backoffice Rides - make Passenger Phone a link to whatsapp

### ISSUE THREAD

**Issue by LEVI-RIVKIN** [Ezer-Lachaim/EZLA#377]
Figma:
https://www.figma.com/file/3UBN2ek01pmm2muttlrxYj/MVP-Current-Design?type=design&node-id=134-107405&mode=dev

Whatsapp Dynamic Link:
https://faq.whatsapp.com/425247423114725/?locale=en_US&cms_platform=iphone

**Comment by YankiBaras** [comment]
Seems to work as expected.
