### ISSUE TITLE
Backoffice Rides - New design for edit and cancel buttons and cancel dialog text change

### ISSUE THREAD

**Issue by LEVI-RIVKIN** [Ezer-Lachaim/EZLA#380]
Buttons Figma:
https://www.figma.com/file/3UBN2ek01pmm2muttlrxYj/MVP-Current-Design?type=design&node-id=1301-330080&mode=dev

Cancel Dialog Figma:
https://www.figma.com/file/3UBN2ek01pmm2muttlrxYj/MVP-Current-Design?type=design&node-id=1301-335074&mode=dev

**Comment by OrleeTal** [comment]
@YankiBaras I do see it in the staging version I'm testing.

**Comment by YankiBaras** [comment]
> @YankiBaras I do see it in the staging version I'm testing.

אכן, היתה טעות בהבנת המשימה. טופל כעת ב-PR שנשלח ב-issue-413.
