### ISSUE TITLE
Correction of character limit for the trip description

### ISSUE THREAD

**Issue by YankiBaras** [Ezer-Lachaim/EZLA#414]
At the moment, the character limit is not rigid, and the hundred character limit can be exceeded. Make the limit rigid.

**Comment by OrleeTal** [comment]
@YankiBaras @yitshak The ride description should be two rows (instead of 1, after which a scrollbar should appear; in the current implementation, the user cannot read the description he wrote.

![Image](https://github.com/Ezer-Lachaim/EZLA/assets/137285852/2533a6b0-aff6-41cc-9b86-d6fd3166fae9)
