### ISSUE TITLE
Backoffice: Navigating between Passengers and Drivers screen, the screen "jumps"

### ISSUE THREAD

**Issue by OrleeTal** [Ezer-Lachaim/EZLA#430]
@YankiBaras @aviv-taori @yosi-miller @yitshak 
As you all worked on the back office, a few bugs were created:

Navigating between the Passengers and Drivers screen, the screen "jumps".
There is probably a problem with the screen resolution.
<img width="129" alt="image" src="https://github.com/Ezer-Lachaim/EZLA/assets/137285852/f34a40c5-33cb-4743-824f-32030b953184">

**Comment by yosi-miller** [comment]
![צילום מסך 2024-02-18 ב-12 47 19](https://github.com/Ezer-Lachaim/EZLA/assets/129267449/7d2590e9-53fa-4c1c-8c34-07130e040e31)

אצלי בדקתי נראה תקין

**Comment by OrleeTal** [comment]
@יוסי מילר - מיגו ***@***.***>
בדקת על מסך של לפ-טופה או מוניטור?
הבעיה היא בלפ טופים.
