### ISSUE TITLE
Backoffice menu design: There should be no underline to text and the width is not in line with the Figma

### ISSUE THREAD

**Issue by OrleeTal** [Ezer-Lachaim/EZLA#431]
@yosi-miller @yitshak 
Backoffice menu design: There should be no underline to text and the width is not in line with the Figma.
<img width="196" alt="image" src="https://github.com/Ezer-Lachaim/EZLA/assets/137285852/1bf3edd2-3f4a-4490-806f-89b9988bf17b">

**Comment by YankiBaras** [comment]
I fixed it in the issue-413 branch. I sent a PR.
